server:
  port: 8081

spring:
  application:
    name: identity
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        show_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


