server:
  port: 8082

spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

kafka:
  bootstrap-servers: localhost:29092


